---
# Project information
site_name: "valorp-HA Addons"
site_url: "https://github.com/valorp/hass-repo"
site_description: ""
site_author: ""
copyright: ""

# Repository
repo_name: "hass-repo"
repo_url: "https://github.com/valorp/hass-repo"
edit_uri: ""

# Theme configuration
theme:
  name: "material"
  logo: "https://avatars3.githubusercontent.com/u/30772201?s=200&v=4"
  language: "en"
  palette:
    primary: "light-blue"
    accent: "blue"
  font:
    text: "Exo2"
    code: "Roboto Mono"
  feature:
    - tabs
extra_css:
  - css/extra.css

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/hassio-addons"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/hassioaddons"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/frenck"
    - icon: fontawesome/brands/twitch
      link: "https://twitch.tv/frenck"
    - icon: fontawesome/brands/youtube
      link: "https://youtube.com/frenck"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/frenck"

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# The pages to serve
nav:
  - "Our Add-ons": "index.md"
  - "Beta Add-ons": "beta.md"
  - "Edge Add-ons": "edge.md"
  - "Contributing": "contributing.md"
  - "Code of Conduct": "code-of-conduct.md"
  - "License": "license.md"
